shellEmulator: true

overrides:
  vite: npm:rolldown-vite@latest

trustPolicy: no-downgrade

onlyBuiltDependencies: [better-sqlite3, sharp]

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  exifreader: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true
  vue-demi: true
